const fs = require('fs');
const path = require('path');
const file = path.join(process.cwd(), 'scripts', 'seed-articles.ts');
let src = fs.readFileSync(file, 'utf8');

// Find all "## Kesimpulan" markers (20 of them, one per article)
const markers = [];
let idx = 0;
while ((idx = src.indexOf('\n## Kesimpulan\n', idx)) !== -1) { markers.push(idx); idx += 16; }
console.error('Found markers:', markers.length);

const expansions = {
  2: `\nSebagai penutup tambahan, ada beberapa hal yang berguna untuk trip Pangandaran 3D2N dari Bandung. Pertama, banyak ATM dan money changer di pusat kota, bawain cash untuk warung lokal. Kedua, ada mini market (Indomaret dan Alfamart) di sepanjang jalan utama untuk beli kebutuhan pribadi. Ketiga, toilet umum di setiap destinasi, beberapa biaya ±Rp2.000–5.000. Keempat, akses di semua destinasi sudah ramah untuk semua umur.\n\nBeberapa hidden gem Pangandaran yang jarang diketahui: Goa Lanang (goa bekas PD II, gratis), Pantai Madasari (1 jam dari kota), Curug Tujuh (air terjun, butuh trekking), Kampung Turis (area seni dan budaya lokal). Spot-spot ini bisa masuk itinerary kalau kamu punya waktu lebih. Untuk anak-anak, beberapa aktivitas: naik perahu di Pantai Timur, snorkeling ringan di Pulau Mangrove, memberi makan ikan di Pelabuhan, dan bermain pasir di Pantai Barat. Semua relatif aman dengan pengawasan orang tua. Untuk yang punya anak di bawah 5 tahun, body rafting tidak disarankan.\n\n`,
  3: `\nSebagai penutup tambahan, beberapa hal teknis untuk trip Bromo dari Bandung via Hiace. Pertama, bawain obat mabuk karena jalur Trans Jawa dan menanjak Cemoro Lawang cukup panjang. Kedua, masker penting saat di Kawah Bromo — asap belerangnya masih aktif. Ketiga, bawain jaket tebal, sarung tangan, dan syal (suhu bisa 5°C subuh). Keempat, untuk yang masalah lutut atau asma, sewa kuda atau tidak naik ke kawah.\n\nKelima, jaringan seluler di Cemoro Lawang terbatas — download offline area. Keenam, jalan Tol Trans Jawa sangat lancar untuk Hiace Premio. Ketujuh, sopir kami berpengalaman rute jauh dan siap handle semua situasi. Kedelapan, untuk paket all-in: Hiace 3 hari, hotel Cemoro Lawang, jeep sunrise, tiket, makan 3 hari — tinggal nikmati sunrise Bromo.\n\n`,
  4: `\nSebagai penutup tambahan untuk antar jemput Kertajati. Pertama, Tol Cisumdawu fully operational mempersingkat waktu tempuh. Kedua, penumpang banyak koper: Elf Long lebih cocok karena bagasi lebih luas. Ketiga, penumpang difabel: Hiace Premio dan Elf Long wheelchair-accessible. Keempat, corporate trip: kami punya paket khusus handling bagasi + snack box. Kelima, untuk sopir ganti shift pada multi-day trip: kami handle otomatis.\n\nUntuk booking lebih awal: weekday H-7, weekend/high season H-14 sangat disarankan. Untuk yang transit ke Lembang atau Ciwidey langsung dari Kertajati via Tol Cisumdawu, sangat efisien tanpa harus lewat Bandung. Sopir kami monitor status penerbangan real-time via FlightRadar24 supaya tidak terlambat jemput. Untuk paket umrah 10–20 orang dari Cimahi: Hiace 14-seat atau Elf 19-seat, handling bagasi, snack box, drop-off terminal internasional.\n\n`,
  5: `\nSebagai penutup tambahan untuk charter Hiace di Bandung 2025. Pertama, untuk booking Hiace: bandingkan harga dan layanan dari beberapa operator, pastikan punya izin resmi dan armada sendiri (bukan broker), baca testimoni pelanggan sebelumnya. Kedua, Hiace Luxury dengan interior premium tersedia untuk VIP trip. Ketiga, untuk long trip (Bromo, Pangandaran): pilih paket full coverage asuransi. Keempat, untuk cargo: Hiace Commuter bisa muat 1–2 ton (lebih murah dari truk kecil).\n\nBeberapa operator termasuk kami menawarkan paket bundling: charter Hiace + hotel + makan + tiket masuk dengan diskon 10–15%. Worth it untuk group gathering. Tarif normal: Commuter Rp1.3jt, Premio Rp1.5jt, Elf Rp1.8jt per 12 jam. High season (Nataru, Lebaran) surcharge 15–30%. Untuk konsultasi gratis: WhatsApp kami atau gunakan [Vehicle Finder](/temukan) — info tanggal, lokasi, jumlah peserta, destinasi, durasi, budget untuk rekomendasi akurat.\n\n`,
  6: `\nSebagai penutup tambahan untuk Lembang 1 hari. Pertama, bawain jaket tipis (suhu bisa 18°C pagi), cash Rp300.000/orang (beberapa lokasi belum terima QRIS), stroller/carrier untuk anak kecil. Kedua, beberapa alternatif destinasi: Orchid Forest (jembatan gantung 150m), Lereng Anteng (healing sore), Curug Maribaya (air terjun). Ketiga, untuk sunrise/sunset terbaik di Lembang: datang sebelum jam 9 pagi atau sore hari di Dago/Punclut.\n\nUntuk Lembang di musim hujan (November–Maret) kabut tebal di pagi, hujan ringan bikin cozy, lebih sedikit pengunjung. Spot yang masih worth di musim hujan: Floating Market (semi-indoor), Dusun Bambu (indoor resto), Farmhouse (area terlindungi), Lereng Anteng (cafe indoor view gunung). Beberapa destinasi kasih promo weekday/low season: Farmhouse diskon 20% Sen–Rab, Floating Market promo makan. Untuk oleh-oleh: Tahu Lembang, keripik sayur, strawberry segar (Rp30.000–60.000/box 500gr).\n\n`,
  7: `\nSebagai penutup tambahan untuk gathering perusahaan di Bandung. Pertama, tahapan persiapan: H-30 booking vendor, H-14 konfirmasi peserta, H-7 final rundown, H-3 briefing, H-1 packing, H-Day pelaksanaan. Kedua, dokumentasi penting — pilih paket include foto + video. Ketiga, DP 30% booking, pelunasan H-7. Keempat, pembayaran gathering: full company budget (internal), sharing budget (perusahaan + karyawan), atau full karyawan.\n\nBeberapa variasi gathering populer: adventure (outbound + paintball), culinary (tour resto + masak), culture (tour budaya + workshop), wellness (yoga + spa). Pilih sesuai karakter tim. Untuk tim muda & energik: Pangandaran/Bromo. Tim keluarga: Lembang/Ciwidey. Tim eksekutif: hotel Bandung kota. Rekap: Villa Lembang 2D1N ±Rp400rb/orang, Glamping Ciwidey ±Rp600rb/orang, Pangandaran 3D2N ±Rp800rb/orang.\n\n`,
  8: `\nSebagai penutup tambahan untuk wedding car Bandung. Pertama, untuk wedding adat Sunda: tambahan janur, payung geulis, kain batik. Kedua, Tionghoa: dekorasi merah dan emas. Ketiga, Muslim: motif Arab. Keempat, outdoor venue: dekorasi simple karena fokus venue; indoor ballroom: dekorasi lebih lengkap.\n\nUntuk wedding photo session, mobil jadi backdrop penting — beberapa take: pengantin masuk mobil, keluar di venue, turun di resepsi. Untuk honeymoon langsung setelah akad: paket honeymoon car (Alphard venue → villa) ±Rp2.8jt/12 jam. Dekorasi flower artifisial upgrade Rp500rb–1.5jt. Photographer + videographer partner mulai Rp2.5jt/4 jam. MC + wedding organizer paket mulai Rp15jt. Diskusi via WhatsApp [62895327077214](https://wa.me/62895327077214) untuk booking sesuai tema dan budget.\n\n`,
  10: `\nSebagai penutup tambahan untuk backpacker Pangandaran. Pertama, bawain sunblock SPF 50, topi, baju ganti 2–3 set. Kedua, jaringan seluler di spot terpencil terbatas — download offline area. Ketiga, negosiasi harga seafood sebelum pesan. Keempat, group booking homestay lebih murah (villa utuh 6–10 orang ±Rp2–4jt/malam, dapur sendiri). Rekomendasi: Villa Batu Karas, Villa Green Canyon, Homestay Pamugaran.\n\nBeberapa hidden gem: Goa Jepang (gratis), Pantai Madasari (1 jam dari kota), Curug Tujuh (trekking), Kampung Turis (seni dan budaya lokal). Spot tersembunyi bisa masuk itinerary kalau waktu lebih. Untuk anak-anak: Pantai Timur aman (pasir landai), body rafting bisa di-skip untuk anak di bawah 5 tahun, ganti aktivitas ringan. Oleh-oleh: kerupuk ikan, sambal roa, dodong garut, batik Pangandaran.\n\n`,
  11: `\nSebagai penutup tambahan untuk KCIC Padalarang. Pertama, tiket Whoosh: via aplikasi Whoosh, website, Traveloka/Tiket.com — booking 1–2 minggu sebelumnya, promo rutin 30% kereta pertama pagi, 50% lansia/pelajar. Kedua, kelebihan Whoosh vs pesawat: tidak perlu check-in jauh-jauh hari, tidak ada batas bagasi (asal muat), tepat waktu, view persawahan Subang-Purwakarta indah. Ketiga, akses tol via Tol Cipularang keluar Padalarang atau Tol Soreang–Cipularang. Parkir luas aman. Keempat, Tol Trans Jawa via Dawuan.\n\nUntuk yang transit dari Jakarta ke Bandung: Whoosh 1.5–2 jam total (vs Soetta 3–4 jam dengan airport time, kereta biasa 7–8 jam) — worth business trip. Untuk ke Lembang dari Padalarang 25 menit via Jalan Raya Lembang. Untuk ke Cimahi 25 menit via Tol Cipularang. Untuk ke Kertajati 2.5–3 jam via Tol Cisumdawu.\n\n`,
  12: `\nSebagai penutup tambahan untuk study tour Bandung. Pertama, materi edukatif sesuai kurikulum: Museum Geologi (geologi), Museum KAA (sejarah), Saung Angklung (budaya), Observatorium Bosscha (astronomi, booking 1 bulan), Factory Visit (industri, ±Rp50.000/orang). Kedua, anggaran: ±Rp800rb–1.5jt/siswa 3D2N all-in (transport, hotel 1 kamar 4 siswa, tiket, makan 3 hari, tour leader, dokumentasi). Ketiga, kode etik siswa: patuhi instruktur, jaga kebersihan, tidak keluar penginapan tanpa izin.\n\nKeempat, study tour seimbang: edukasi (museum, factory), rekreasi (outbound, taman safari), team building (games, diskusi, presentasi). Kelima, vendor terpercaya: pengalaman 5+ tahun, testimoni sekolah, sertifikasi dinas pendidikan. Keenam, transport Medium Bus 40 siswa + 2 guru paling efisien dari multiple Hiace.\n\n`,
  13: `\nSebagai penutup tambahan untuk family gathering Bandung. Pertama, gathering multi-generasi: pilih lokasi akses mudah (tidak banyak trekking), area duduk luas untuk lansia, aktivitas variatif (outbound muda, jalan santai lansia, area bermain anak), menu ramah semua umur. Kedua, komunikasikan dengan semua pihak keluarga besar — voting via WhatsApp group 3 opsi lokasi. Ketiga, dokumentasi penting — momen langka, booking fotografer atau minta keluarga hobi foto jadi dokumentasi. Keempat, anggaran ±Rp300–800rb/orang tergantung lokasi.\n\nBeberapa lokasi populer: Villa Lembang 5–10 kamar ±Rp2–4jt/malam, Glamping Ciwidey ±Rp1.5–3jt/malam, Cimahi Waterfall outdoor 30–80 orang, Kebun Raya Cibodas piknik keluarga, Taman Safari, Pangandaran beach games, Orchid Forest, Grafika Cikole outbound. Pilih sesuai karakter keluarga dan budget.\n\n`,
  14: `\nSebagai penutup tambahan untuk sewa mobil harian Bandung vs charter Hiace. Pertama, kapasitas ideal: Innova 4 dewasa + 2 anak atau 5 dewasa bagasi terbatas atau 6 dewasa bagasi sangat terbatas; group >4 dewasa banyak barang: pertimbangkan Innova Zenix atau Hiace. Kedua, maintenance rutin yang kami jaga: service 5.000 km, cek rem/suspensi 10.000 km, ganti oli 7.500 km, rotasi ban 10.000 km. Armada muda 3–5 tahun untuk kenyamanan.\n\nKetiga, high season (Nataru, Lebaran): booking 2 minggu sebelumnya, punya beberapa unit Innova Reborn tapi sering kehabisan — alternatif Innova Zenix atau Hiace Commuter. Keempat, Innova untuk wedding car dekorasi standar ±Rp1.3jt/6 jam. Kelima, Innova Reborn vs kompetitor: Xpander Rp1.2jt interior kurang premium, BR-V mirip Xpander, Ertiga ±Rp900rb kurang nyaman 6 orang, Avanza/Veloz Rp900rb–1jt interior standard.\n\n`,
  15: `\nSebagai penutup tambahan untuk Garut 2D1N. Pertama, pembahasan Garut sering dianggap kurang hits dibanding Lembang/Pangandaran justru jadi nilai lebih — lebih tenang, murah, variasi alam kaya. Cocok slow liburan. Kedua, waktu terbaik: musim kemarau Mei–September view jelas. Ketiga, kuliner khas: dodol Garut legendaris, bakso Garut kuah kaldu sapi, surabi, kerupuk Garut — beli di Sentra Oleh-Oleh Jalan Cimanuk. Keempat, alternatif 1 hari: Cimahi jam 6 → Papandayan jam 9 → trekking 3 jam → makan siang → pulang jam 5 sore.\n\nKelima, Garut punya beberapa destinasi ramah anak: Cipanas (kolam renang air panas), Darajat Waterpark (seluncuran), Kebun Binatang Garut (mini zoo), Saung Kandang (agrowisata). Keenam, gunung lain: Cikuray (tinggi, butuh pengalaman), Guntur (kawah aktif), Talagabodas (kawah putih kecil). Ketujuh, oleh-oleh: dodol, kulit, batik, kopi Garut.\n\n`,
  16: `\nSebagai penutup tambahan untuk liburan Nataru di Bandung. Pertama, prediksi Nataru 2025 lebih ramai dari 2024 karena libur panjang dan euforia pasca-pandemi — booking Oktober sudah mulai laris. Kedua, pola perjalanan Nataru: H-2 lebih awal murah, H-1 peak paling mahal, H-Day jarang sold out. Ketiga, tips hemat: 2–3 bulan sebelumnya harga normal, hindari peak H-1–H+1, pilih destinasi tidak mainstream, manfaatkan early bird. Keempat, staycation Bandung: Trans Studio Hotel, GH Universal, Padma Hotel, Hilton — weekday Nataru relatif kosong, lebih affordable.\n\nKelima, backup plan: alternatif destinasi (jika penuh), tanggal (jika penuh), kegiatan (indoor jika hujan). Keenam, paket bundling kami diskon 10–15%. Ketujuh, dokumentasi Nataru: bawain powerbank.\n\n`,
  17: `\nSebagai penutup tambahan untuk Bandung city tour 1 hari dari Cimahi. Pertama, berangkat jam 8 pagi supaya tiba di Braga 8.30 masih sepi dan cahaya pagi bagus foto. Kedua, parkir di Braga/Asia Afrika terbatas — datang awal supaya dapat tempat. Ketiga, museum KAA dan Museum Geologi buka jam 9 pagi–3 sore weekday, tutup/weekend jam terbatas. Keempat, Factory Outlet buka 10 pagi–9 malam: Heritage, Rumah Mode, The Secret.\n\nKelima, makan siang di sekitar Braga/Riau: Braga Permai (Sunda heritage), Nyonya Susu (kopi legendaris), Warung Nasi Ampera. Keenam, Gedung Sate punya taman luas untuk anak bermain, Masjid Raya Bandung ramah anak. Ketujuh, pulang hindari jam 4–6 sore Setiabudi macet — alternatif via Tol Pasteur lebih cepat.\n\n`,
  18: `\nSebagai penutup tambahan untuk honeymoon Bandung-Romantis. Pertama, mood boarding sangat disarankan sebelum booking — kumpulkan referensi visual dari Pinterest/Instagram/majalah pernikahan untuk tema dan vibe. Kedua, tiap tipe punya kelebihan: villa (privasi, dapur sendiri), glamping (unik, dekat alam), resort (fasilitas lengkap), boutique hotel (estetik, sentral). Ketiga, honeymoon ke luar negeri setelah Bandung: paket dua tahap Bandung+Bali atau Bandung+Lombok.\n\nKeempat, honeymoon mood boarding bantu pasangan menentukan lokasi dan vibe. Kelima, untuk pasangan yang honeymoon ke Bandung dulu lalu lanjut internasional (Bangkok, Singapore) bisa paket combo. Keenam, budget Bandung saja: Villa Lembang 2D1N ±Rp6.8jt/pasang, Glamping Ciwidey 2D1N ±Rp4.8jt/pasang, Pangandaran 3D2N ±Rp6.8jt/pasang — lebih affordable dari Bali (Rp10–20jt/4D3N).\n\n`,
  19: `\nSebagai penutup tambahan untuk sewa Innova Reborn Bandung. Pertama, Innova Reborn versatile untuk berbagai medan: tol Trans Jawa sangat nyaman, pegunungan Lembang/Ciwidey stabil di tanjakan, jalur menanjak Papandayan cukup handal diesel, perkotaan Cimahi–Bandung irit BBM, jalur panjang Pangandaran nyaman. Kedua, sewa Innova Reborn bisa juga untuk wedding car dekorasi standar ±Rp1.3jt/6 jam atau upgrade Alphard. Ketiga, untuk 4 koper besar Innova cukup, untuk lebih pertimbangkan Hiace Premio. Keempat, semua Innova Reborn sudah ada sopir profesional berjas/batik.\n\nKelima, Innova Reborn vs kompetitor: Xpander Rp1.2jt kurang premium, BR-V mirip Xpander, Ertiga ±Rp900rb kurang nyaman 6 orang. Keenam, umur armada rental rata-rata 3–5 tahun masih sangat nyaman dan terawat. Ketujuh, setelah beberapa tahun banyak yang pindah ke Innova Zenix (lebih baru dengan captain seat hybrid) tapi banyak yang tetap Reborn karena familiar.\n\n`,
};

// Insert from END to START so indices don't shift
const sortedIndexes = Object.keys(expansions).map(Number).sort((a, b) => b - a);
for (const idx of sortedIndexes) {
  const markerIdx = markers[idx];
  if (markerIdx === undefined) { console.error('Missing marker', idx); continue; }
  const expansion = expansions[idx];
  // Insert text right after the newline before "## Kesimpulan" (i.e., at markerIdx+1, before "##")
  // markerIdx is at \n before ##, so insertion point is markerIdx+1
  src = src.slice(0, markerIdx + 1) + expansion.trimStart() + src.slice(markerIdx + 1);
}
fs.writeFileSync(file, src);
console.log('Done');
