const fs=require('fs'),p=require('path'),f=p.join(process.cwd(),'scripts','seed-articles.ts');let s=fs.readFileSync(f,'utf8');
const idxs=[...s.matchAll(/\n## Kesimpulan\n/g)].map(m=>m.index);
const exps={
4: `\nUntuk paket antar jemput yang lebih lengkap, cek juga layanan [paket wisata lainnya](/paket) kami. Sopir kami sudah hafal titik jemput dan drop di sekitar Cimahi, Bandung kota, Padalarang, hingga Lembang. Untuk group umrah yang jadwalnya mepet dengan penerbangan, kami juga bisa handle penjemputan dini hari (surcharge 20% jam 22.00–05.00). Selalu konfirmasi jadwal H-1 via WhatsApp untuk memastikan tidak ada perubahan flight yang terlewat. Untuk paket Kertajati 2025 dengan harga update, hubungi kami untuk penawaran terbaik.\n\n`,
5: `\nUntuk konsultasi lebih lanjut, gunakan [Vehicle Finder](/temukan) kami — jawab beberapa pertanyaan tentang jumlah penumpang dan budget untuk rekomendasi otomatis. Atau langsung hubungi WhatsApp untuk diskusi kebutuhan trip kamu. Sopir kami hafal rute Bandung Raya dan siap kasih rekomendasi spot makan atau rest area terbaik selama perjalanan. Untuk paket wisata dengan Hiace yang lebih lengkap, cek [paket kami](/paket) untuk bundling transport+hotel+makan+tiket.\n\n`,
6: `\nUntuk booking transport Lembang 1 hari dari Cimahi, cek [Vehicle Finder](/temukan) untuk rekomendasi otomatis berdasarkan jumlah penumpang dan durasi. Atau lihat [katalog armada](/armada) lengkap kami: Toyota Calya 4 seat, Innova Reborn 6 seat, Hiace Commuter 14 seat, Hiace Premio 14 seat premium, Elf Long 19 seat, Alphard premium. Semua sudah include sopir berpengalaman dan BBM dalam kota, exclude tol dan tiket wisata.\n\n`,
10: `\nUntuk paket backpacker Pangandaran yang lebih hemat lagi, pertimbangkan naik travel PP dan homestay budget. Atau untuk group 4–6 orang, patungan rental Innova Reborn sharing Rp300rb/orang 3 hari cuma Rp900rb/orang include BBM dan sopir. Cek [paket Pangandaran](/paket) untuk perbandingan harga charter vs travel. Banyak oleh-oleh Pangandaran di jalan tol: kerupuk ikan, sambal roa, dodong garut asli Garut, batik. Sopir kami tahu spot oleh-oleh terbaik yang tidak terlalu mahal.\n\n`,
11: `\nUntuk paket Whoosh + wisata Lembang/Ciwidey/Pangandaran dari Padalarang, cek [paket kami](/paket) untuk bundling. Atau diskusi via WhatsApp [62895327077214](https://wa.me/62895327077214) untuk itinerary custom. Sopir kami bisa standby di titik jemput Padalarang sesuai jadwal kedatangan kereta — informasikan nomor kereta dan jam tiba untuk penyesuaian. Untuk akses parkir dan tol, kami sudah hafal jalur tercepat dari Padalarang ke berbagai destinasi Bandung Raya.\n\n`,
12: `\nUntuk paket study tour yang lebih lengkap, cek [paket study tour](/paket) kami atau kontak WhatsApp untuk diskusi jumlah siswa dan destinasi. Sopir Medium Bus kami sudah terbiasa handle group sekolah besar dan tahu titik parkir untuk bus di setiap destinasi Bandung. Untuk booking study tour dari luar Jawa, kami handle penjemputan di bandara atau stasiun — termasuk Kertajati atau Halim via KCIC Whoosh.\n\n`,
13: `\nUntuk paket family gathering yang lebih lengkap, cek [paket gathering](/paket) kami untuk 15–100 orang dengan variasi lokasi Lembang, Ciwidey, Pangandaran, Garut, Bandung kota. Atau diskusi via WhatsApp [62895327077214](https://wa.me/62895327077214) untuk gathering custom. Sopir Hiace Premio kami tahu lokasi gathering terbaik dan titik parkir untuk group besar. Untuk catering dan snack box, vendor kami bisa customize menu untuk multi-generasi.\n\n`,
15: `\nUntuk paket Garut 2D1N yang lebih lengkap, cek [paket Garut](/paket) kami: Hiace Premio 2 hari, hotel Cipanas dengan private hot spring, makan 3x, tiket masuk, dan jeep sunrise Papandayan. DP 30% konfirmasi, pelunasan H-3. Sopir Hiace Premio kami tahu jalur Limbangan dan Kadungora, titik istirahat, dan warung makan terbaik di Garut. Untuk booking study tour Garut dari sekolah, kami handle Medium Bus untuk 40 siswa.\n\n`,
17: `\nUntuk paket Bandung city tour yang lebih lengkap, cek [paket city tour](/paket) kami: Innova Reborn 12 jam, guide opsional ±Rp500.000/12 jam, makan siang, dan dokumentasi. Atau kombinasi 2 hari city tour + Lembang via [itinerary Lembang](/artikel/itinerary-lembang-1-hari) sangat populer untuk traveler luar kota. Sopir Innova Reborn kami hafal titik heritage Braga/Asia Afrika dan bisa rekomendasi cafe hidden dengan konsep vintage.\n\n`,
18: `\nUntuk paket honeymoon yang lebih lengkap, cek [paket honeymoon](/paket) kami: transport Alphard/Innova Zenix, villa/glamping, private dinner romantis, spa couple, photographer opsional, dan dekorasi. DP 30% konfirmasi. Sopir Alphard kami tampil premium dan sudah terbiasa handle honeymoon car dengan dekorasi bunga dan lilin. Untuk surprise keluarga, koordinasi setup di villa sangat berkesan dan personal.\n\n`,
};
let n=0;
for(const [k,v] of Object.entries(exps)){
  const i=Number(k),pos=idxs[i];
  if(pos===undefined){console.error('miss',k);continue;}
  s=s.slice(0,pos+1)+v.trimStart()+s.slice(pos+1);n++;
}
fs.writeFileSync(f,s);console.log('done',n);