const fs=require('fs'),p=require('path'),f=p.join(process.cwd(),'scripts','seed-articles.ts');let s=fs.readFileSync(f,'utf8');
const idxs=[...s.matchAll(/\n## Kesimpulan\n/g)].map(m=>m.index);
console.error('markers',idxs.length);
const exps={
4: `\nSebagai penutup tambahan untuk antar jemput Bandara Kertajati. Pertama, untuk penerbangan yang delay, sopir kami monitor real-time dan standby 1 jam setelah jadwal baru. Kedua, untuk group umrah 10–20 orang dari Cimahi, Hiace 14-seat atau Elf 19-seat dengan handling bagasi + snack box. Ketiga, untuk penumpang banyak koper: Elf Long bagasi 2× Innova. Keempat, corporate trip: paket khusus untuk karyawan yang terbang umrah bersama. Kelima, untuk penumpang difabel: wheelchair-accessible Hiace/Elf, sopir assist naik-turun. Keenam, untuk rute langsung Kertajati→Lembang/Ciwidey via Tol Cisumdawu tanpa lewat Bandung — sangat efisien.\n\nUntuk booking: weekday H-7, weekend/high season H-14 disarankan. Cek [antar jemput Kertajati](/artikel/antar-jemput-bandara-kertajati-dari-cimahi-bandung) untuk detail tarif. Sopir bantu muat dan turun bagasi, handling profesional untuk koper besar.\n\n`,
5: `\nSebagai penutup tambahan untuk tarif charter Hiace Bandung 2025. Pertama, untuk booking Hiace: bandingkan harga dan layanan, pastikan izin resmi dan armada sendiri (bukan broker), baca testimoni pelanggan. Kedua, Hiace Luxury interior premium tersedia untuk VIP trip dengan audio entertainment dan mini bar. Ketiga, long trip (Bromo, Pangandaran): pilih full coverage asuransi (deductible Rp500rb–1jt). Keempat, untuk cargo: Hiace Commuter muat 1–2 ton lebih murah dari truk kecil. Kelima, untuk rute populer: Cimahi→Lembang 30 menit half-day charter, Cimahi→Ciwidey 1.5–2 jam full-day, Bandung→Pangandaran 6–7 jam overnight, Bandung→Bromo 12–14 jam 3 hari.\n\nUntuk konsultasi gratis: WhatsApp kami atau gunakan [Vehicle Finder](/temukan) — info tanggal, lokasi, jumlah peserta, destinasi, durasi, budget untuk rekomendasi akurat. Paket bundling (armada+hotel+makan+tiket) diskon 10–15% worth untuk group gathering.\n\n`,
6: `\nSebagai penutup tambahan untuk itinerary Lembang 1 hari optimal. Pertama, 1 hari ideal untuk 3 destinasi utama: Tangkuban Perahu→Farmhouse→Floating Market→De Ranch atau Dusun Bambu. Kedua, untuk anak kecil: Farmhouse (mini zoo), Floating Market (area bermain), Dusun Bambu (playground) — hindari Tangkuban karena jalur menurun kurang ramah stroller. Ketiga, Floaring Market voucher Rp50.000 sudah include di tiket, bisa beli makanan tradisional dari perahu. Keempat, Dusun Bambu: resto Sunda panorama danau, workshop bambu dan lampion.\n\nUntuk kombinasi 2 hari Lembang+Ciwidey sangat populer: hari 1 Lembang, hari 2 Ciwidey dengan glamping. Cek [itinerary Ciwidey 2 hari](/artikel/itinerary-ciwidey-2-hari-1-malam) untuk detail. Untuk 3 hari Lembang+Pangandaran juga available untuk family yang punya waktu lebih.\n\n`,
7: `\nSebagai penutup tambahan untuk paket gathering perusahaan Bandung. Pertama, tahapan persiapan: H-30 booking vendor+lokasi, H-14 konfirmasi peserta+rundown, H-7 final rundown+teknis, H-3 briefing, H-1 packing, H-Day pelaksanaan. Kedua, dokumentasi penting — pilih paket include foto+video untuk content internal dan sosmed. Ketiga, DP 30% booking, pelunasan H-7, pembatalan H-7 full refund. Keempat, beberapa paket populer: Lembang 1 hari Rp350rb/orang 30–80 orang, Ciwidey 2D1N Rp1.1jt 40–100 orang, Pangandaran 3D2N Rp1.8jt 30–60 orang.\n\nUntuk aktivitas outbound, vendor partner kami fasilitator bersertifikat, games: ice breaking, trust fall, Amazing Race, paintball, flying fox, refleksi. Kombinasi 3–4 games untuk acara 4–6 jam. Sound system + dokumentasi sudah include.\n\n`,
8: `\nSebagai penutup tambahan untuk wedding car Bandung premium. Pertama, untuk wedding adat Sunda: tambahan janur, payung geulis, kain batik. Tionghoa: merah+emas. Muslim: motif Arab. Kedua, outdoor venue dekorasi simple, indoor ballroom lebih lengkap — pita putih + bunga sederhana, upgrade flower artifisial Rp500rb–1.5jt. Ketiga, photo session: pengantin masuk mobil, keluar venue, turun resepsi — beberapa kali take. Keempat, honeymoon langsung setelah akad: paket honeymoon car Alphard venue→villa ±Rp2.8jt/12 jam.\n\nUntuk multi-mobil: 1 Alphard untuk intimate 50–80 tamu, 2 Alphard atau Alphard+Hiace Premio untuk 200+ tamu. Beberapa pengantin sewa Fortuner/Innova keluarga dekat. Konsultasi via WhatsApp [62895327077214](https://wa.me/62895327077214) untuk booking sesuai tema dan budget wedding kamu. Sopir tampil rapi default jas/batik formal.\n\n`,
10: `\nSebagai penutup tambahan untuk backpacker Pangandaran murah dari Cimahi. Pertama, bawain sunblock SPF50, topi, baju ganti 2–3 set, obat pribadi. Kedua, jaringan seluler spot terpencil terbatas — download offline area. Ketiga, negosiasi seafood sebelum pesan, jangan lupa topi. Keempat, group booking homestay lebih murah (villa utuh 6–10 orang ±Rp2–4jt/malam dapur sendiri: Villa Batu Karas, Green Canyon, Homestay Pamugaran). Kelima, aktivitas tambahan: sunset Batu Karas, snorkeling Pulau Mangrove Rp150.000/orang, body rafting tanpa guide sungai atas Citumang gratis butuh pengalaman.\n\nUntuk oleh-oleh Pangandaran: kerupuk ikan, sambal roa, dodong garut, batik Pangandaran, kaos Pangandaran. Beberapa mini market (Indomaret, Alfamart) di sepanjang jalan utama untuk kebutuhan pribadi. Toilet umum Rp2.000–5.000, beberapa free.\n\n`,
11: `\nSebagai penutup tambahan untuk Stasiun KCIC Padalarang Whoosh. Pertama, tiket Whoosh: aplikasi Whoosh/website/Traveloka/Tiket.com — booking 1–2 minggu sebelumnya, promo 30% kereta pertama pagi, 50% lansia/pelajar. Kedua, kelebihan vs pesawat: tanpa check-in jauh, tanpa batas bagasi (asal muat), tepat waktu, view persawahan Subang-Purwakarta indah. Ketiga, akses tol via Tol Cipularang keluar Padalarang atau Soreang–Cipularang, parkir luas aman Rp10.000/mobil. Keempat, shuttle free parkir→stasiun. Kelima, Tol Trans Jawa via Dawuan, Jakarta→Bandung 1.5–2 jam total (vs Soetta 3–4 jam, kereta biasa 7–8 jam) worth business trip.\n\nUntuk ke Lembang dari Padalarang 25 menit via Jalan Raya Lembang, ke Cimahi 25 menit via Tol Cipularang, ke Kertajati 2.5–3 jam via Tol Cisumdawu.\n\n`,
12: `\nSebagai penutup tambahan untuk paket study tour Bandung untuk sekolah 3 hari. Pertama, materi edukatif sesuai kurikulum: Museum Geologi (geologi), Museum KAA (sejarah), Saung Angklung Rp100.000/orang (budaya, workshop), Observatorium Bosscha ITB (astronomi, booking 1 bulan), CV Logam ±Rp50.000 (industri). Kedua, anggaran: ±Rp800rb–1.5jt/siswa 3D2N all-in (transport sharing 40 siswa Medium Bus Rp350rb, hotel 1 kamar 4 siswa Rp350rb, tiket+workshop Rp150rb, makan Rp250rb, leader+dokumentasi Rp100rb). Ketiga, kode etik siswa: patuhi instruktur, jaga kebersihan, tidak keluar penginapan tanpa izin.\n\nKeempat, study tour seimbang: edukasi (museum, factory), rekreasi (outbound, taman safari), team building (games, diskusi, presentasi). Kelima, vendor terpercaya pengalaman 5+ tahun, testimoni sekolah, sertifikasi dinas pendidikan.\n\n`,
13: `\nSebagai penutup tambahan untuk family gathering Bandung 10 ide lokasi outing seru. Pertama, gathering multi-generasi: lokasi akses mudah (tidak banyak trekking), area duduk luas lansia, aktivitas variatif (outbound muda, jalan santai lansia, area bermain anak), menu ramah semua umur (tidak pedas, bubur/nasi tim anak). Kedua, komunikasikan semua pihak keluarga besar — voting via WhatsApp group 3 opsi lokasi. Ketiga, dokumentasi penting — momen langka, booking fotografer atau keluarga hobi foto jadi dokumentasi. Keempat, anggaran ±Rp300–800rb/orang tergantung lokasi, makan, transport, aktivitas.\n\nBeberapa lokasi populer: Villa Lembang 5–10 kamar ±Rp2–4jt/malam kolam renang view gunung, Glamping Ciwidey ±Rp1.5–3jt/malam, Cimahi Waterfall outdoor 30–80 orang, Kebun Raya Cibodas piknik keluarga, Dusun Bambu, Taman Safari, Pangandaran beach games, Bandung kota + FO, Orchid Forest, Grafika Cikole outbound.\n\n`,
14: `\nSebagai penutup tambahan untuk sewa mobil harian Bandung vs charter Hiace mana hemat. Pertama, Innova 4 dewasa+2 anak ideal, 5 dewasa bagasi terbatas, 6 dewasa sangat terbatas; group >4 dewasa banyak barang: Hiace/Incova Zenix. Kedua, maintenance rutin kami: service 5.000 km, cek rem/suspensi 10.000 km, ganti oli 7.500 km, rotasi ban 10.000 km — armada muda 3–5 tahun nyaman. Ketiga, high season (Nataru, Lebaran): booking 2 minggu sebelumnya, punya beberapa unit Innova Reborn tapi sering habis alternatif Zenix/Hiace. Keempat, Innova wedding car dekorasi standar ±Rp1.3jt/6 jam. Kelima, Innova vs kompetitor: Xpander Rp1.2jt kurang premium, BR-V mirip Xpander, Ertiga ±Rp900rb kurang nyaman 6 orang, Avanza/Veloz Rp900rb–1jt standard.\n\nUntuk corporate trip: paket khusus handling bagasi+snack box. Untuk backpacker: group booking homestay lebih murah.\n\n`,
15: `\nSebagai penutup tambahan untuk itinerary Garut 2D1N Papandayan Darajat Cipanas. Pertama, Garut sebagai hidden gem — tenang, murah, variasi alam kaya, cocok slow liburan dibanding Lembang/Pangandaran yang mainstream. Kedua, waktu terbaik musim kemarau Mei–September view jelas. Ketiga, kuliner khas: dodol Garut legendaris, bakso Garut kuah kaldu sapi, surabi legit, kerupuk Garut — Sentra Jalan Cimanuk. Keempat, alternatif 1 hari: Cimahi jam6→Papandayan jam9→trekking 3 jam→makan siang→pulang jam5. Kelima, ramah anak: Cipanas kolam renang air panas, Darajat Waterpark seluncuran, Kebun Binatang mini zoo, Saung Kandang agrowisata.\n\nKeenam, gunung lain: Cikuray tinggi butuh pengalaman, Guntur kawah aktif, Talagabodas kawah putih kecil. Ketujuh, oleh-oleh: dodol, kulit, batik, kopi Garut.\n\n`,
16: `\nSebagai penutup tambahan untuk tips liburan akhir tahun high season 2025 di Bandung. Pertama, prediksi Nataru 2025 lebih ramai dari 2024 karena libur panjang dan euforia pasca-pandemi — booking Oktober sudah laris. Kedua, pola: H-2 awal murah, H-1 peak mahal, H-Day jarang sold out. Ketiga, hemat: booking 2–3 bulan sebelumnya harga normal, hindari peak H-1–H+1, destinasi tidak mainstream, early bird. Keempat, staycation Bandung: Trans Studio Hotel, GH Universal, Padma Hotel, Hilton — weekday Nataru kosong affordable. Kelima, backup plan: destinasi alternatif jika penuh, tanggal alternatif, kegiatan indoor jika hujan.\n\nKeenam, paket bundling diskon 10–15% worth keluarga besar. Ketujuh, dokumentasi Nataru bawain powerbank.\n\n`,
17: `\nSebagai penutup tambahan untuk Bandung city tour 1 hari dari Cimahi. Pertama, berangkat jam8 pagi tiba di Braga 8.30 masih sepi cahaya pagi bagus foto. Kedua, parkir Braga/Asia Afrika terbatas datang awal. Ketiga, museum KAA dan Museum Geologi buka jam9 pagi–3 sore weekday, weekend terbatas. Keempat, Factory Outlet buka 10 pagi–9 malam: Heritage, Rumah Mode, The Secret. Kelima, makan siang Braga/Riau: Braga Permai (Sunda heritage), Nyonya Susu (kopi legendaris), Warung Nasi Ampera. Keenam, Gedung Sate punya taman luas anak bermain, Masjid Raya ramah anak. Ketujuh, pulang hindari jam4–6 sore Setiabudi macet — alternatif via Tol Pasteur lebih cepat.\n\nUntuk kombinasi 2 hari: hari1 city tour, hari2 Lembang via [itinerary Lembang](/artikel/itinerary-lembang-1-hari) sangat populer.\n\n`,
18: `\nSebagai penutup tambahan untuk paket honeymoon Bandung-Romantis 5 destinasi favorit. Pertama, mood boarding sangat disarankan — kumpulkan referensi Pinterest/Instagram/majalah untuk tema dan vibe. Kedua, tiap tipe kelebihan: villa (privasi+dapur), glamping (unik+dekat alam), resort (fasilitas lengkap), boutique hotel (estetik+sentral). Ketiga, kombinasi paket Bandung saja (Lembang+Ciwidey), Bandung+Bali, Bandung+Lombok, Bandung internasional (Bangkok, Singapore). Keempat, budget Bandung saja: Villa Lembang 2D1N ±Rp6.8jt/pasang, Glamping Ciwidey 2D1N ±Rp4.8jt/pasang, Pangandaran 3D2N ±Rp6.8jt/pasang — lebih affordable dari Bali (Rp10–20jt/4D3N).\n\nUntuk surprise keluarga: dekorasi kamar bunga+lilin, kue surprise, scrapbook kenangan sangat berkesan. Untuk dokumentasi: photographer honeymoon mulai Rp2.5jt/4 jam.\n\n`,
};
let n=0;
for(const [k,v] of Object.entries(exps)){
  const i=Number(k),pos=idxs[i];
  if(pos===undefined){console.error('miss',k);continue;}
  s=s.slice(0,pos+1)+v.trimStart()+s.slice(pos+1);n++;
}
fs.writeFileSync(f,s);console.log('done',n);